fix: board not closed when sending and event cancellation.
Zextras/carbonio-calendars-ui pull request #156
Opened 2022-10-11 17:41 UTC by dhavaldodiya

board not closed when sending and event cancellation.

2022-10-12 07:07 UTC, geeky-abhishek approved these changes

2022-10-12 07:07 UTC, geeky-abhishek commented on src/hooks/use-delete-actions.ts
> +						onBoardClose();
for safety add a condition onBoardClose && onBoardClose()

2022-10-14 07:35 UTC, giuliano176 approved these changes

2022-10-14 08:06 UTC, nubsthead requested changes, later dismissed
Jenkins pipeline fails during type check

2022-10-24 10:57 UTC, gnekoz approved these changes

2022-10-24 10:57 UTC, merged