fix: propose new time fixed
Zextras/carbonio-calendars-ui pull request #162
Opened 2022-10-21 13:48 UTC by geeky-abhishek

2022-10-24 12:12 UTC, gnekoz approved these changes

2022-10-25 07:20 UTC, giuliano176 requested changes

2022-10-25 07:20 UTC, giuliano176 commented on src/view/editor/parts/editor-organizer.tsx
> +	const normalizedOrganizer = normaliseContact(organizer);
in this case the type should be fixed

2022-10-25 07:48 UTC, giuliano176 approved these changes

2022-10-25 07:56 UTC, merged