fix: show full description instead of fragment
Zextras/carbonio-calendars-ui pull request #20
Opened 2022-02-15 14:12 UTC by geeky-abhishek

2022-02-17 08:07 UTC, zovomat commented on src/shared/invite-response/parts/invite-reply-part.tsx
> +						label="PROPOSE NEW TIME"
these need to be translated

2022-02-17 08:30 UTC, nubsthead requested changes
There is an issue with appointments description css.
![image](https://user-images.githubusercontent.com/62339254/154436028-92352f78-3f92-4843-b1f8-9fe104938991.png)

2022-02-17 08:30 UTC, nubsthead commented on src/shared/invite-response/parts/invite-reply-part.tsx
> +						label="PROPOSE NEW TIME"
missing translation key

2022-02-21 09:34 UTC, dhavaldodiya submitted a review, later dismissed

2022-02-21 11:09 UTC, giuliano176 reviewed
I did test on a random invite and the fragment is not rendering 
in my test BodyMessageRenderer is not composed correctly, fullinvite.textDescription is undefined

2022-02-22 06:52 UTC, geeky-abhishek commented
> I did test on a random invite and the fragment is not rendering in my test BodyMessageRenderer is not composed correctly, fullinvite.textDescription is undefined ![Screenshot_20220221_114838](https://user-images.githubusercontent.com/75381134/154943817-5defd5b2-4a68-4ed3-9794-2b4463f8234e.png)

@giuliano176 It's because it's not an invite.You can check on zimbra also XD

2022-02-22 08:59 UTC, nubsthead submitted a review, later dismissed

2022-02-23 13:32 UTC, zovomat approved these changes, later dismissed

2022-02-23 13:33 UTC, zovomat approved these changes

2022-02-23 13:40 UTC, nubsthead approved these changes

2022-02-23 13:45 UTC, merged