chore: replace the files action
Zextras/carbonio-calendars-ui pull request #236
Opened 2023-02-22 11:09 UTC by dhavaldodiya

2023-02-23 09:49 UTC, gnekoz approved these changes, later dismissed

2023-02-23 10:09 UTC, CMazzilli commented on src/view/editor/parts/editor-attachments-button.tsx
>  			...filesSelectFilesAction,
this destructuring is no more required

2023-02-23 11:50 UTC, gnekoz approved these changes, later dismissed

2023-02-23 13:16 UTC, CataldoMazzilli commented on src/view/editor/parts/editor-attachments-button.tsx
> +			...getFilesAction,
remove "...getFilesAction" it is a function

2023-02-23 13:16 UTC, CMazzilli commented on src/view/editor/parts/editor-attachments-button.tsx
>  			...getFilesAction,
remove "...getFilesAction" it is a function

2023-02-23 13:17 UTC, CMazzilli requested changes
build is failing

2023-02-24 08:36 UTC, nubsthead submitted a review, later dismissed

2023-02-27 09:21 UTC, CMazzilli submitted a review, later dismissed

2023-02-28 10:04 UTC, gnekoz submitted a review, later dismissed

2023-02-28 10:33 UTC, giuliano176 approved these changes

2023-02-28 10:43 UTC, CMazzilli approved these changes

2023-02-28 10:49 UTC, nubsthead approved these changes

2023-02-28 10:50 UTC, merged