fix: remove html link
Zextras/carbonio-calendars-ui pull request #295
Opened 2023-05-30 13:28 UTC by Gammax92

2023-05-31 06:52 UTC, dhavaldodiya approved these changes, later dismissed

2023-06-05 07:35 UTC, nubsthead requested changes

2023-06-05 07:35 UTC, nubsthead commented on src/view/sidebar/edit-modal/parts/share-calendar-url-modal.tsx
>  	const domain =
can you also modify this line of code? It makes no sense to hardcode crb2
```suggestion
	const domain = window.location.hostname
```

2023-06-06 04:42 UTC, dhavaldodiya approved these changes

2023-06-06 07:09 UTC, nubsthead approved these changes

2023-06-06 08:50 UTC, merged