fix: focus on composer new appointment input during appointment creation
Zextras/carbonio-calendars-ui pull request #298
Opened 2023-06-19 07:58 UTC by Gammax92

2023-06-19 08:06 UTC, dhavaldodiya approved these changes

2023-06-19 15:58 UTC, nubsthead requested changes

2023-06-19 15:58 UTC, nubsthead commented on src/view/editor/parts/editor-title.tsx
> +			label={`${t('label.event_title', 'Event title')}*`}
Why do you add an asterisk inside the title?

2023-06-20 07:40 UTC, gnekoz approved these changes

2023-06-20 15:00 UTC, FrancescoGottardi commented on src/view/editor/parts/editor-title.tsx
> +			label={`${t('label.event_title', 'Event title')}*`}
the field is now required and start empty, i interpolated it insted of putting the asterisk inside the translation.
Should i change the implementation?

2023-06-20 15:35 UTC, nubsthead commented on src/view/editor/parts/editor-title.tsx
> +			label={`${t('label.event_title', 'Event title')}*`}
Oh ok, I didn't notice it was a desiderata of the task

2023-06-20 15:36 UTC, nubsthead approved these changes

2023-06-21 15:15 UTC, gnekoz approved these changes

2023-08-17 14:19 UTC, nubsthead requested changes
Implement the mandatory code to set to false the editor auto focus

2023-09-29 13:11 UTC, closed without merging