Iris 4636 cannot change color editing a shared calendar
Zextras/carbonio-calendars-ui pull request #332
Opened 2023-09-15 13:54 UTC by Gammax92

2023-09-15 13:55 UTC, gnekoz submitted a review, later dismissed

2023-09-15 14:01 UTC, nubsthead requested changes
Still not working when shared with 1 person

2023-09-18 07:08 UTC, nubsthead approved these changes

2023-09-18 07:33 UTC, giuliano176 approved these changes

2023-09-18 07:37 UTC, merged