add new optional attribute type in folderactionrequest for empty…
Zextras/carbonio-calendars-ui pull request #459
Opened 2024-06-07 09:54 UTC by mananpatel13589

… operation

2024-06-07 09:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zextras/carbonio-calendars-ui?pullRequest=459) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zextras/carbonio-calendars-ui?pullRequest=459) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zextras/carbonio-calendars-ui?pullRequest=459) it.</sub>

2024-06-07 14:08 UTC, dhavaldodiya submitted a review, later dismissed

2024-06-10 15:03 UTC, nubsthead requested changes
As this work will change the behaviour of the trash operation, also the modal string should be changed accordingly to reflect the correct operation

2024-06-11 08:34 UTC, mananpatel13589 commented
> As this work will change the behaviour of the trash operation, also the modal string should be changed accordingly to reflect the correct operation

Updated confirmation message
[Ticket] (https://zextras.atlassian.net/browse/CO-1186?focusedCommentId=56513)

2024-06-11 13:23 UTC, nubsthead approved these changes

2024-06-12 06:06 UTC, dhavaldodiya approved these changes

2024-06-12 06:14 UTC, merged