feat: optionals attendees implemented
Zextras/carbonio-calendars-ui pull request #62
Opened 2022-05-09 11:20 UTC by dhavaldodiya

optionals attendees implemented

2022-05-09 11:26 UTC, nubsthead approved these changes

2022-05-09 12:33 UTC, zovomat commented on src/view/event-panel-edit/editor-complete-view.jsx
> +	const [ContactInput] = useIntegratedComponent('contact-input');
the `available` flag should be used, to check if the integration is available before using it

2022-05-10 06:13 UTC, geeky-abhishek approved these changes

2022-05-10 07:29 UTC, nubsthead approved these changes

2022-05-10 07:35 UTC, giuliano176 requested changes

2022-05-10 07:35 UTC, giuliano176 commented on src/view/event-panel-edit/editor-complete-view.jsx
> +const emailRegex =
please use this regex instead, so that we can keep support for the Cyrillic language:

/[^\s@]+@[^\s@]+\.[^\s@]+/;

2022-05-10 08:18 UTC, nubsthead approved these changes

2022-05-10 08:26 UTC, zovomat approved these changes

2022-05-10 09:26 UTC, giuliano176 approved these changes

2022-05-10 12:19 UTC, merged