Workweek fix iris 2442
Zextras/carbonio-calendars-ui pull request #67
Opened 2022-05-16 15:29 UTC by gnekoz

2022-05-16 15:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/Zextras/carbonio-calendars-ui?pullRequest=67) <br/>All committers have signed the CLA.

2022-05-18 13:44 UTC, geeky-abhishek commented
@gnekoz the only problem I found out in this new work week implementation is, when the user first time open it's work week view it's blank
![Screenshot 2022-05-18 at 7 08 33 PM](https://user-images.githubusercontent.com/74703491/169053129-d0b56520-b2c7-42b9-ad90-f24d83918398.png)
 
and second is when you update your work week schedule from the calendar's settings it is not automatically updated.The view will update once you navigate

2022-05-19 07:30 UTC, nubsthead requested changes
Need to fix an issue which render empty calendar on refresh

2022-05-20 08:27 UTC, geeky-abhishek approved these changes

2022-05-20 14:11 UTC, zovomat approved these changes

2022-05-20 14:12 UTC, nubsthead approved these changes

2022-05-20 14:20 UTC, merged